clear all;
d = [];
R_data = [];
load('mdisim_0km.mat');
R_data = [R_data,R];
d = [d,0];
load('mdisim_5km.mat');
R_data = [R_data,R];
d = [d,5];
load('mdisim_10km.mat');
R_data = [R_data,R];
d = [d,10];
load('mdisim_20km.mat');
R_data = [R_data,R];
d = [d,20];
load('mdisim_30km.mat');
R_data = [R_data,R];
d = [d,30];
load('mdisim_40km.mat');
R_data = [R_data,R];
d = [d,40];
load('mdisim_50km.mat');
R_data = [R_data,R];
d = [d,50];
load('mdisim_55km.mat');
R_data = [R_data,R];
d = [d,55];
load('mdisim_65km.mat');
R_data = [R_data,R];
d = [d,65];
load('mdisim_70km.mat');
R_data = [R_data,R];
d = [d,70];
load('mdisim_75km.mat');
R_data = [R_data,R];
d = [d,75];
R_data(end) = 1e-10;
semilogy(d,R_data);
xlabel("Transmission Distance(km)");
ylabel("Key Generation Rate");